공지사항 관련 기능 리팩토링
ch0213/admin-site-server pull request #71
Opened 2022-10-11 03:33 UTC by ch0213

안녕하세요 동규님~ 공지사항 관련 기능을 리팩터링했습니다.
하나의 PR의 크기를 줄이고 피드백 주기를 빠르게 가져가야되는데 다음 PR에는 더 줄여보도록 하겠습니다 😅
잘 부탁드립니다!

### 리팩터링 포인트

1. AggregateRoot를 통해서만 접근하도록 했습니다.
2. 공지사항은 Member를 직접 참조하지 않고 MemberId를 통해 간접 참조합니다.
    - 대부분의 컨텍스트에서는 Member를 참조합니다. 공통으로 사용하기 위해 Author(id, email, studentNumber, name, role)라는 VO를 만들고 common 패키지에 위치시켰습니다.
    - 데이터의 일관성을 맞추기 위해 Member의 정보가 변경될 때 이벤트를 발행하고, 다른 컨텍스트에서 이벤트를 수신해 Author에 변경 사항을 반영합니다.
3. 비대한 응용계층, 빈약한 도메인 ⇒ 얇은 응용계층, 풍부한 도메인
    - 기존 응용 계층에 있던 로직을 도메인으로 이동시켰습니다.
        - 변경, 삭제를 위한 인증
    - 리스트 관련 기능은 일급 컬렉션으로 분리해 처리했습니다.
    - 각 객체에 책임이 적절하게 분산되어 코드의 복잡도가 낮아졌고, 테스트 하기 수월해졌습니다.
4. 하나의 트랜잭션에서는 최소한의 작업만 하도록 변경했습니다.
    - 기존에는 게시물이 삭제되거나, 게시물의 첨부파일이 변경될 때 S3에 삭제, 저장 요청을 보냈습니다.
    - 리팩터링 후에는 공지사항을 변경하거나 삭제할 때 S3 저장소에서 AnnouncmentFilePath를 soft delete 하도록 했습니다. 실제 저장소의 이미지 삭제는 트랜잭션 내에서 하지 않고, 배치 작업으로 분리했습니다. 배치 작업은 모든 도메인 리팩터링 후 적용할 계획입니다.
5. 단위 테스트, 인수 테스트를 작성해 개발한 기능에 대한 안정성을 높였습니다.

resolves #59, #69

2022-10-16 23:50 UTC, brainbackdoor commented
댓글의 생애주기가 공지사항, 갤러리, 질문 등 각각의 도메인에 종속된다면 말씀하신 것처럼 하위도메인으로 두는 것이 자연스럽다고 생각해요.

2022-10-16 23:55 UTC, brainbackdoor requested changes
리팩토링 정말 잘 진행해주셨네요! 💯 
단위 테스트, 테스트 구조나 픽스처, 가독성 등에서 긍정적인 인상을 주었고, 인위적으로 infrastructure layer를 나눠보려고 시도한 점도 인상적이었어요~
특히 정책 부분을 README로 표현해주셔서 읽기 수월했어요~ (덕분에 생각보다 빠르게 피드백할 수 있었네요 😬)
몇가지 이해가 안되는 부분이 있어서 피드백 남겨두었는데요. 확인하고 Approve 할게요~
이번 주 면접 일정이 있다고 들었는데요. 잘 준비하셔서 좋은 결과 있길 바랄게요~ 🙏🏻

2022-10-16 23:55 UTC, brainbackdoor commented on src/main/java/admin/adminsiteserver/announcement/application/AnnouncementService.java
> +        announcementRepository.flush();
아, JpaRepository를 infrastructure layer로 나누었군요.

2022-10-16 23:55 UTC, brainbackdoor commented on src/main/java/admin/adminsiteserver/announcement/infra/AnnouncementEventListener.java
> +    @Async
현재는 Thread pool를 각 컨텍스트가 기본 Pool로 같이 사용하고 있겠군요.

2022-10-16 23:55 UTC, brainbackdoor commented on src/main/java/admin/adminsiteserver/announcement/domain/Announcement.java
> +    private Author author;
common에 있지만, 실제로는 announcement 테이블의 칼럼이군요..?

2022-10-16 23:55 UTC, brainbackdoor commented on src/main/java/admin/adminsiteserver/announcement/infra/AnnouncementEventListener.java
> +        announcements.forEach(announcement -> announcement.updateAuthor(event.getAuthor()));
memberService에서 update commit 발생시점에 에러가 발생한다면, 어떤 현상이 발생할까요?
혹은 updateAuthor 진행 중 에러가 발생할 경우, 어떤 현상이 발생할까요?

2022-10-16 23:55 UTC, brainbackdoor commented on src/main/java/admin/adminsiteserver/announcement/ui/AnnouncementController.java
> +            @AuthenticationPrincipal LoginMember loginMember
👍🏻

2022-10-16 23:55 UTC, brainbackdoor commented on src/main/java/admin/adminsiteserver/announcement/application/AnnouncementService.java
> +        Announcement announcement = request.toEntity(loginMember);
파일 업로드가 있어서 upload인줄 알았는데, 실제로 업로드가 이루어지는건 아니군요..?
파일 이름과 url을 등록하는거군요.

2022-10-16 23:55 UTC, brainbackdoor commented on src/test/java/admin/adminsiteserver/AcceptanceTest.java
> +        saveMembers();
테스트마다 디비를 초기화하는 건가요? 케이스가 많아지면 이 부분이 테스트 성능 저하지점이 되지 않을까요

2022-10-16 23:55 UTC, brainbackdoor commented on src/test/java/admin/adminsiteserver/announcement/domain/AnnouncementCommentTest.java
> +    @DisplayName("작성한 사람보다 접근 권한이 높을 경우 공지사항 댓글을 수정할 수 있다.")
권한이 낮을 경우에 대한 테스트들이 없군요.

2022-10-16 23:55 UTC, brainbackdoor commented on src/main/java/admin/adminsiteserver/announcement/domain/AnnouncementFilePath.java
> +        this(null, fileName, fileUrl);
URL이면 URL 형식에 대한 유효성 검증이 필요하지 않을까요

2022-10-16 23:55 UTC, brainbackdoor commented on src/test/java/admin/adminsiteserver/announcement/fixture/AnnouncementCommentFixture.java
> +    회원_공지사항댓글(9L, "안녕하세요 회원입니다.", 회원.getAuthor());
👍🏻

2022-10-28 14:08 UTC, ch0213 commented on src/main/java/admin/adminsiteserver/announcement/application/AnnouncementQueryService.java
> +        return PageResponse.of(announcements.getContent(), PageInformation.from(announcements));
repository를 통해 조회하는 기능을 find를 선택했고, 그 외의 경우 `명사`를 사용하도록 했습니다. 말씀하신대로 명사를 사용하니 의미가 더 잘 전달되는 것 같습니다.

2022-10-28 14:11 UTC, ch0213 commented on src/main/java/admin/adminsiteserver/announcement/application/AnnouncementQueryService.java
> +        return announcementRepository.findByIdAndDeletedIsFalse(announcementId)
처음에 동규님이 말씀해주신 것 처럼 어노테이션을 사용해서 soft delete를 구현할까 했지만, `삭제한다` 자체도 단위테스트를 통해 검증해야할 기능이라고 생각해서 직접 구현했습니다. 동규님은 soft delete를 구현할 때 어노테이션을 사용해서 구현하는걸 선호하시나요?

2022-10-28 14:12 UTC, ch0213 commented on src/main/java/admin/adminsiteserver/authentication/domain/LoginMember.java
> +        return new Author(id, email, studentNumber, name, roleType);
이 부분 제거했습니다!

2022-10-28 14:15 UTC, ch0213 commented on src/main/java/admin/adminsiteserver/announcement/domain/Announcement.java
> +        comments.updateAuthor(author);
이 부분은 event listener에서 사용하는 로직으로, 회원의 정보가 변경되었을 때 게시물의 작성자 정보에 반영하는 부분입니다. 말씀하신대로 변경 로직을 별도로 제공해보려 했는데 어떤 방식으로 제공해야할지 감이 잘 안오네요. 이 부분 의견 여쭤봐도 될까요?

2022-10-28 14:23 UTC, ch0213 commented on src/main/java/admin/adminsiteserver/announcement/domain/AnnouncementFilePaths.java
> +        this.files.addAll(files);
로직이 잘못되었네요. 수정했습니다 😅

2022-10-28 14:24 UTC, ch0213 commented on src/main/java/admin/adminsiteserver/announcement/domain/AnnouncementComment.java
> +        this(null, comment, author);
Content를 VO로 추출해 길이를 검증하도록 했습니다.

2022-10-28 14:28 UTC, ch0213 commented on src/test/java/admin/adminsiteserver/AcceptanceTest.java
> +        saveMembers();
Rest assured를 사용하다보니 `@Transactoinal`이 적용되지 않아 테스트 격리를 위해 데이터를 매 번 초기화했습니다.
씨유님은 Rest assured를 사용할 때 테스트간 격리를 위해 어떤 방법을 사용하시나요?

2022-10-28 15:27 UTC, ch0213 commented
회원 정보 변경은 유실되면 안되는 중요한 이벤트기 때문에 이벤트 히스토리를 저장했습니다. 아래 그림처럼 이벤트 발행과 이벤트 히스토리 기록을 하나의 트랜잭션으로 처리해서 이벤트가 기록되지 않으면 발행이 실패하도록 했습니다. 또한 이벤트를 발행하는 `MemberService`의 `update`가 커밋 도중 실패할 수 있기 때문에 `AnnouncementEventListener`에서는 `@TransactionalEventListener`를 통해 커밋된 후에 해당 이벤트를 처리하도록 했습니다. 이벤트가 정상적으로 발행되고, 이벤트 히스토리도 기록되었지만 `MemberEvent`를 처리하는 `AnnouncementEventListener`에서 실패할 수 있기 때문에 `EventHsitory`에 `processed(=false)`라는 상태를 두고, `AnnouncementEventListener`가 정상적으로 처리한 경우에 `process` 처리합니다. 실패한 이벤트는 주기적으로 배치 작업을 통해 다시 처리됩니다. 이 때 같은 종류의 이벤트가 두 번 이상 유실될 수 있고, 이런 경우에는 발생 순서가 중요하므로 `eventDataTime`이라는 필드를 추가했습니다. 따라서 한 번 발행된 이벤트는 유실되지 않고 처리되며, 최종적 일관성이 보장됩니다.

<img width="562" alt="아키텍처" src="https://user-images.githubusercontent.com/49121847/198672666-573dcc32-cbb0-4552-a920-5502e8a87356.png">

### 참고
[회원시스템 이벤트기반 아키텍처 구축하기](https://www.youtube.com/watch?v=b65zIH7sDug&t=1028s)

2022-10-28 15:32 UTC, ch0213 commented
회원 정보 변경은 유실되면 안되는 중요한 이벤트기 때문에 이벤트 히스토리를 저장했습니다. 아래 그림처럼 이벤트 발행과 이벤트 히스토리 기록을 하나의 트랜잭션으로 처리해서 이벤트가 기록되지 않으면 발행이 실패하도록 했습니다. 또한 이벤트를 발행하는 `MemberService`의 `update`가 커밋 도중 실패할 수 있기 때문에 `AnnouncementEventListener`에서는 `@TransactionalEventListener`를 통해 커밋된 후에 해당 이벤트를 처리하도록 했습니다. 이벤트가 정상적으로 발행되고, 이벤트 히스토리도 기록되었지만 `MemberEvent`를 처리하는 `AnnouncementEventListener`에서 실패할 수 있기 때문에 `EventHsitory`에 `processed(=false)`라는 상태를 두고, `AnnouncementEventListener`가 정상적으로 처리한 경우에 `process` 처리합니다. 실패한 이벤트는 주기적으로 배치 작업을 통해 다시 처리됩니다. 이 때 같은 종류의 이벤트가 두 번 이상 유실될 수 있고, 이런 경우에는 발생 순서가 중요하므로 `eventDateTime`이라는 필드를 추가했습니다. 따라서 한 번 발행된 이벤트는 유실되지 않고 처리되며, 최종적 일관성이 보장됩니다.

<img width="562" alt="아키텍처" src="https://user-images.githubusercontent.com/49121847/198672666-573dcc32-cbb0-4552-a920-5502e8a87356.png">

### 참고
[회원시스템 이벤트기반 아키텍처 구축하기](https://www.youtube.com/watch?v=b65zIH7sDug&t=992s)

2022-11-02 19:56 UTC, brainbackdoor commented
이번 케이스는 Outbox 혹은 Log tailing 패턴 등을 활용한 이벤트소싱 등을 고려할 필요까진 없다고 생각해요.
`@TransactionalEventListner`를 활용하여 원자성을 보장하는 것에 대해 생각해보셨는지 피드백 남긴거였어요~

2022-11-02 20:03 UTC, ch0213 commented on src/main/java/admin/adminsiteserver/announcement/domain/AnnouncementComment.java
> +    }
이 부분 질문을 남긴다는걸 깜빡했네요. 특정 게시물을 지울 때 포함된 파일 및 댓글 또한 모두 deleted 상태가 되는데 이를 위해서 생성한 메서드입니다. 이런 경우 강제 삭제가 불가피하다고 생각되는데 어떻게 생각하시나요?

2022-11-02 20:32 UTC, brainbackdoor commented on src/main/java/admin/adminsiteserver/announcement/domain/Announcement.java
> +        comments.updateAuthor(author);
아, 게시글 작성자가 아닌 사용자의 정보가 바뀐 경우엔, 댓글 작성자 정보가 변경되지 않을 것 같다는 의미였는데요.
제가 코드를 잘못봤었나 보네요 😅 자신이 작성한 게시글의 댓글을 수정하는 로직으로 보고 남겼던 피드백이라 무시하시면 됩니다.

2022-11-02 20:41 UTC, ch0213 commented on src/main/java/admin/adminsiteserver/announcement/domain/AnnouncementComments.java
> +        return comment.getId().equals(commentId) && !comment.isDeleted();
아이고 이 부분을 놓쳤군요..😅

2022-11-02 20:42 UTC, brainbackdoor approved these changes
피드백 반영 확인했어요~ 👍🏻 
이번 리팩토링은 여기서 머지할게요~ 
학습하고 적용하고 성장하는 모습 좋습니다~ 앞으로도 파이팅입니다! 💪🏻

2022-11-02 20:42 UTC, brainbackdoor commented on src/test/java/admin/adminsiteserver/AcceptanceTest.java
> +        saveMembers();
저는 테스트에 필요한 유저 세팅(given)은 테스트 내에서 진행하는 편입니다. 
given 절이 길어지는게 우려라면 Fixture를 작성하고, 메소드를 분리하여 코드를 정리하는 편입니다.

2022-11-02 20:46 UTC, merged